language: android
android:
    components:
        - platform-tools
        - tools

        # The Gradle BuildTools version
        - build-tools-23.0.2

        # The SDK Version
        - android-23

        # Additional Components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19

        # System Image
        - sys-img-armeabi-v7a-android-23
notifications:
  slack: getexposure:AFuZVRjjgSeBKsJMuaKhJQJU
before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
# whitelist
branches:
  only:
    - master
    - develop